Script started on 2016年03月14日 (週一) 01時03分44秒
[01;32mF74044038@2015cpp[00m:[01;34m~/lab1[00m$ whoami;pwd
F74044038
/home/F74044038/lab1
[01;32mF74044038@2015cpp[00m:[01;34m~/lab1[00m$ git config-l
git: 'config-l' is not a git command. See 'git --help'.
[01;32mF74044038@2015cpp[00m:[01;34m~/lab1[00m$ git config-l -l[C[C
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
remote.origin.url=https://github.com/F74044038/lab1.git
branch.master.remote=origin
branch.master.merge=refs/heads/master
[01;32mF74044038@2015cpp[00m:[01;34m~/lab1[00m$ git clone https://github.com/F74044038/lab1.git[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[K[Kexit

Script done on 2016年03月14日 (週一) 01時05分28秒
